- name: Check if xcversion is installed
  shell: PATH=/usr/local/bin:$PATH && command -v xcversion > /dev/null
  register: xcversion_exists
  ignore_errors: yes

- name: Debug
  debug:
    var: xcversion_exists.rc

- name: Check if xcode already installed
  shell: PATH=/usr/local/bin:$PATH && xcversion installed
  register: xcode_install_status
  when: xcversion_exists.rc == 0

- name: Install Xcode with xcversion
  shell: export XCODE_INSTALL_USER={{ APPLE_ID_USER }}; export XCODE_INSTALL_PASSWORD={{ APPLE_ID_PASS }}; PATH=/usr/local/bin:$PATH && xcversion install "{{ item.version }}"
  with_items: "{{ xcode_config }}"
  when: xcversion_exists.rc == 0 and xcode_install_status.stdout == "" and not item.install_from_package
