---
  # Java special setup due to issues via homebrew module

  - name: Create askpass script
    shell: printf "#!/bin/sh\necho {{SUDO_PASS}}\n" > {{temp.path}}/askpass &&  chmod u+x {{temp.path}}/askpass && export SUDO_ASKPASS={{temp.path}}/askpass
    register: askpass

  - name: Install java cask
    shell: export SUDO_ASKPASS={{temp.path}}/askpass && export PATH=/usr/local/bin:$PATH && brew cask install java
